import json

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.employee import Employee
from app.models.knowledge_base import KnowledgeBase, KnowledgeEntry


async def export_markdown(db: AsyncSession, employee: Employee) -> str:
    """Export an employee's knowledge base as formatted Markdown."""
    kb_result = await db.execute(
        select(KnowledgeBase).where(KnowledgeBase.employee_id == employee.id)
    )
    kb = kb_result.scalar_one_or_none()
    if not kb:
        raise ValueError("No knowledge base found for this employee")

    entries_result = await db.execute(
        select(KnowledgeEntry)
        .where(KnowledgeEntry.knowledge_base_id == kb.id)
        .order_by(KnowledgeEntry.category, KnowledgeEntry.title)
    )
    entries = entries_result.scalars().all()

    # Build markdown document
    md = f"# Knowledge Base: {employee.full_name}\n\n"
    md += f"**Role:** {employee.job_title} | **Department:** {employee.department}\n"
    md += f"**Tenure:** {employee.tenure_years} years\n\n"
    md += "---\n\n"

    # Group by category
    categories: dict[str, list] = {}
    for entry in entries:
        categories.setdefault(entry.category, []).append(entry)

    category_titles = {
        "workflows": "Workflows & Processes",
        "decisions": "Decision-Making & Judgment",
        "relationships": "Relationships & Stakeholders",
        "workarounds": "Workarounds & Undocumented Steps",
        "history": "Historical Context & Institutional Memory",
    }

    for cat, cat_entries in categories.items():
        md += f"## {category_titles.get(cat, cat.title())}\n\n"
        for entry in cat_entries:
            md += f"### {entry.title}\n\n"
            md += f"{entry.content}\n\n"
            if entry.tags:
                tags = json.loads(entry.tags)
                if tags:
                    md += f"**Tags:** {', '.join(tags)}\n\n"
            md += "---\n\n"

    md += f"\n*Generated by Offboardly — {kb.synthesis_completed_at or 'Draft'}*\n"
    return md
